const CANDIDATE_STATUSES = Object.freeze({
  NEW_RECEIVED: 'NEW_RECEIVED',
  PAID0_DOCS_SUBMITTED: 'PAID0_DOCS_SUBMITTED',
  WAITING_FORM_MATCH: 'WAITING_FORM_MATCH',
  FORM_MATCHED_WAITING_EXAM: 'FORM_MATCHED_WAITING_EXAM',
  PASSED: 'PASSED',
  FAILED_POOL: 'FAILED_POOL'
});

const STATUS_ORDER = Object.freeze([
  CANDIDATE_STATUSES.NEW_RECEIVED,
  CANDIDATE_STATUSES.PAID0_DOCS_SUBMITTED,
  CANDIDATE_STATUSES.WAITING_FORM_MATCH,
  CANDIDATE_STATUSES.FORM_MATCHED_WAITING_EXAM,
  CANDIDATE_STATUSES.PASSED,
  CANDIDATE_STATUSES.FAILED_POOL
]);

const TRANSITIONS = Object.freeze({
  [CANDIDATE_STATUSES.NEW_RECEIVED]: [CANDIDATE_STATUSES.PAID0_DOCS_SUBMITTED],
  [CANDIDATE_STATUSES.PAID0_DOCS_SUBMITTED]: [CANDIDATE_STATUSES.WAITING_FORM_MATCH],
  [CANDIDATE_STATUSES.WAITING_FORM_MATCH]: [CANDIDATE_STATUSES.FORM_MATCHED_WAITING_EXAM],
  [CANDIDATE_STATUSES.FORM_MATCHED_WAITING_EXAM]: [
    CANDIDATE_STATUSES.PASSED,
    CANDIDATE_STATUSES.FAILED_POOL
  ],
  [CANDIDATE_STATUSES.FAILED_POOL]: [CANDIDATE_STATUSES.WAITING_FORM_MATCH],
  [CANDIDATE_STATUSES.PASSED]: []
});

function isValidStatus(status) {
  return Object.values(CANDIDATE_STATUSES).includes(status);
}

function canTransition(currentStatus, nextStatus) {
  if (!isValidStatus(currentStatus) || !isValidStatus(nextStatus)) {
    return false;
  }

  if (currentStatus === nextStatus) {
    return true;
  }

  const allowed = TRANSITIONS[currentStatus] || [];
  return allowed.includes(nextStatus);
}

module.exports = {
  CANDIDATE_STATUSES,
  STATUS_ORDER,
  isValidStatus,
  canTransition
};